apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flaskr
  name: flaskr
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskr
  type: LoadBalancer
status:
  loadBalancer: {}
